import {Note} from "@/app/shared/lib/common-types";

export type KeyboardKeyItem = { note: Note, type: 'white' | 'black', enabled: boolean, octave: number };

export type KeyData = {
    note: Note;
    octave: number;
}

export const defaultKeyboardMap: Array<KeyboardKeyItem> = [
    {note: 'A', type: 'white', enabled: true, octave: 0},
    {note: 'A#', type: 'black', enabled: true, octave: 0},
    {note: 'B', type: 'white', enabled: true, octave: 0},
    {note: 'C', type: 'white', enabled: true, octave: 1},
    {note: 'C#', type: 'black', enabled: true, octave: 1},
    {note: 'D', type: 'white', enabled: true, octave: 1},
    {note: 'D#', type: 'black', enabled: true, octave: 1},
    {note: 'E', type: 'white', enabled: true, octave: 1},
    {note: 'F', type: 'white', enabled: true, octave: 1},
    {note: 'F#', type: 'black', enabled: true, octave: 1},
    {note: 'G', type: 'white', enabled: true, octave: 1},
    {note: 'G#', type: 'black', enabled: true, octave: 1},
    {note: 'A', type: 'white', enabled: true, octave: 1},
    {note: 'A#', type: 'black', enabled: true, octave: 1},
    {note: 'B', type: 'white', enabled: true, octave: 1},
    {note: 'C', type: 'white', enabled: true, octave: 2},
    {note: 'C#', type: 'black', enabled: true, octave: 2},
    {note: 'D', type: 'white', enabled: true, octave: 2},
    {note: 'D#', type: 'black', enabled: true, octave: 2},
    {note: 'E', type: 'white', enabled: true, octave: 2},
    {note: 'F', type: 'white', enabled: true, octave: 2},
    {note: 'F#', type: 'black', enabled: true, octave: 2},
    {note: 'G', type: 'white', enabled: true, octave: 2},
    {note: 'G#', type: 'black', enabled: true, octave: 2},
    {note: 'A', type: 'white', enabled: true, octave: 2},
    {note: 'A#', type: 'black', enabled: true, octave: 2},
    {note: 'B', type: 'white', enabled: true, octave: 2},
    {note: 'C', type: 'white', enabled: true, octave: 3},
    {note: 'C#', type: 'black', enabled: true, octave: 3},
    {note: 'D', type: 'white', enabled: true, octave: 3},
    {note: 'D#', type: 'black', enabled: true, octave: 3},
    {note: 'E', type: 'white', enabled: true, octave: 3},
    {note: 'F', type: 'white', enabled: true, octave: 3},
    {note: 'F#', type: 'black', enabled: true, octave: 3},
    {note: 'G', type: 'white', enabled: true, octave: 3},
    {note: 'G#', type: 'black', enabled: true, octave: 3},
    {note: 'A', type: 'white', enabled: true, octave: 3},
    {note: 'A#', type: 'black', enabled: true, octave: 3},
    {note: 'B', type: 'white', enabled: true, octave: 3},
    {note: 'C', type: 'white', enabled: true, octave: 4},
    {note: 'C#', type: 'black', enabled: true, octave: 4},
    {note: 'D', type: 'white', enabled: true, octave: 4},
    {note: 'D#', type: 'black', enabled: true, octave: 4},
    {note: 'E', type: 'white', enabled: true, octave: 4},
    {note: 'F', type: 'white', enabled: true, octave: 4},
    {note: 'F#', type: 'black', enabled: true, octave: 4},
    {note: 'G', type: 'white', enabled: true, octave: 4},
    {note: 'G#', type: 'black', enabled: true, octave: 4},
    {note: 'A', type: 'white', enabled: true, octave: 4},
    {note: 'A#', type: 'black', enabled: true, octave: 4},
    {note: 'B', type: 'white', enabled: true, octave: 4},
    {note: 'C', type: 'white', enabled: true, octave: 5},
    {note: 'C#', type: 'black', enabled: true, octave: 5},
    {note: 'D', type: 'white', enabled: true, octave: 5},
    {note: 'D#', type: 'black', enabled: true, octave: 5},
    {note: 'E', type: 'white', enabled: true, octave: 5},
    {note: 'F', type: 'white', enabled: true, octave: 5},
    {note: 'F#', type: 'black', enabled: true, octave: 5},
    {note: 'G', type: 'white', enabled: true, octave: 5},
    {note: 'G#', type: 'black', enabled: true, octave: 5},
    {note: 'A', type: 'white', enabled: true, octave: 5},
    {note: 'A#', type: 'black', enabled: true, octave: 5},
    {note: 'B', type: 'white', enabled: true, octave: 5},
    {note: 'C', type: 'white', enabled: true, octave: 6},
    {note: 'C#', type: 'black', enabled: true, octave: 6},
    {note: 'D', type: 'white', enabled: true, octave: 6},
    {note: 'D#', type: 'black', enabled: true, octave: 6},
    {note: 'E', type: 'white', enabled: true, octave: 6},
    {note: 'F', type: 'white', enabled: true, octave: 6},
    {note: 'F#', type: 'black', enabled: true, octave: 6},
    {note: 'G', type: 'white', enabled: true, octave: 6},
    {note: 'G#', type: 'black', enabled: true, octave: 6},
    {note: 'A', type: 'white', enabled: true, octave: 6},
    {note: 'A#', type: 'black', enabled: true, octave: 6},
    {note: 'B', type: 'white', enabled: true, octave: 6},
    {note: 'C', type: 'white', enabled: true, octave: 7},
    {note: 'C#', type: 'black', enabled: true, octave: 7},
    {note: 'D', type: 'white', enabled: true, octave: 7},
    {note: 'D#', type: 'black', enabled: true, octave: 7},
    {note: 'E', type: 'white', enabled: true, octave: 7},
    {note: 'F', type: 'white', enabled: true, octave: 7},
    {note: 'F#', type: 'black', enabled: true, octave: 7},
    {note: 'G', type: 'white', enabled: true, octave: 7},
    {note: 'G#', type: 'black', enabled: true, octave: 7},
    {note: 'A', type: 'white', enabled: true, octave: 7},
    {note: 'A#', type: 'black', enabled: true, octave: 7},
    {note: 'B', type: 'white', enabled: true, octave: 7},
    {note: 'C', type: 'white', enabled: true, octave: 8}
];
